services:
  postgres:
    image: postgres:16
    container_name: cosmo-postgres
    environment:
      POSTGRES_DB: cosmo
      POSTGRES_USER: cosmo
      POSTGRES_PASSWORD: cosmo
    ports:
      - "5432:5432"
    volumes:
      - cosmo_pg:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: cosmo-keycloak
    command: ["start-dev"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  cosmo_pg:
