server:
  port: 8080

spring:
  application:
    name: cosmo-srm

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/cosmo
    username: cosmo
    password: cosmo

  datasource:
    url: jdbc:postgresql://localhost:5432/cosmo
    username: cosmo
    password: cosmo

  liquibase:
    enabled: true
    drop-first: false
    default-schema: public
    liquibase-schema: public
    url: jdbc:postgresql://localhost:5432/cosmo
    user: cosmo
    password: cosmo
    change-log: classpath:/db/changelog/db.changelog-master.yml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/cosmo

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security: INFO
